---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planespotter-frontend
  namespace: planespotter-app
  labels:
    app: planespotter-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planespotter-app
      tier: frontend
  template:
    metadata:
      labels:
        app: planespotter-app
        tier: frontend
        version: v1
    spec:
      containers:
      - name: planespotter-fe
        image: yfauser/planespotter-frontend:d0b30abec8bfdbde01a36d07b30b2a3802d9ccbb
        imagePullPolicy: IfNotPresent
        env:
        - name: PLANESPOTTER_API_ENDPOINT
          value: planespotter-be
        - name: TIMEOUT_REG
          value: "5"
        - name: TIMEOUT_OTHER
          value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: planespotter-frontend
  namespace: planespotter-app
  labels:
    app: planespotter-app
    tier: frontend
spec:
  ports:
    # the port that this service should serve on
    - port: 80
  selector:
    app: planespotter-app
    tier: frontend
#---
#apiVersion: extensions/v1beta1
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
  #name: planespotter-frontend
  #namespace: planespotter-app
#spec:
  #rules:
  #- host: planespotter.demo.yves.local
    #http:
      #paths:
      #- backend:
          #serviceName: planespotter-frontend
          #servicePort: 80
