kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
  namespace: planespotter-app
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: default
  labels:
    app: planespotter-app
    component: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
